//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/CameraControll/CameraActionMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CameraActionMap: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CameraActionMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CameraActionMap"",
    ""maps"": [
        {
            ""name"": ""CameraControll"",
            ""id"": ""8606129b-ff98-4cd8-8b5d-edb20642ad01"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""d89cce40-5730-4727-bcde-6440be7bd7fb"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SprintCamera"",
                    ""type"": ""Button"",
                    ""id"": ""92d4981c-7eef-4ca4-a28f-fcefc8072036"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateCamera"",
                    ""type"": ""Value"",
                    ""id"": ""93a693cf-4770-41c0-821e-0726925e529d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Scroll_In_Out"",
                    ""type"": ""Value"",
                    ""id"": ""0ac2dbd2-9f8c-47bb-83ea-8c83bc8dc7aa"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""e53bee25-acc0-4d86-bc23-6e823ae6591d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Deselect"",
                    ""type"": ""Button"",
                    ""id"": ""e3245b4e-6531-48f5-9e77-ac4f744ef0e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FollowSpecificObject"",
                    ""type"": ""Button"",
                    ""id"": ""cdc8214d-cd2c-4d89-a2f2-88b7fc7fcd6f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateAroundPivot"",
                    ""type"": ""Value"",
                    ""id"": ""490cc914-7aa8-4883-b73f-d62cc00ddc87"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""OpenMenu"",
                    ""type"": ""Button"",
                    ""id"": ""75c4794a-aa4f-483b-84e0-066dd404b2a0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""test"",
                    ""type"": ""Button"",
                    ""id"": ""a6f94f35-b482-4456-a1dd-4b9804aadf42"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SetPivotPoint"",
                    ""type"": ""Value"",
                    ""id"": ""891e6f46-94a4-47e1-9be8-c98075ac7290"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""wasd"",
                    ""id"": ""f068f80e-bfe7-4bc8-a898-581ab1fb2c4b"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""5556791a-c565-4a25-b725-bf28d3efa46b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""9b4c87f9-6b23-49ee-a9e5-27d025872ede"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""0a165af3-2e1d-44dd-97cf-c8b7f43d3b66"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""40668d7e-2d9e-4323-9149-42703b4db56f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Forward"",
                    ""id"": ""0f1ab410-4b88-4607-a96f-1090673595cc"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Backward"",
                    ""id"": ""4f3f8bd4-e5d6-428d-8ebe-ea48b168d038"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""arrowkeys"",
                    ""id"": ""28ebd113-8c46-4ebd-901d-2b91d404721f"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""5a8cce28-9178-426a-8358-041a29513edf"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""035955c6-77c9-4369-9fd4-029b66f433f7"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""a59d3e58-8894-43ee-98b2-72424db88aee"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""0c23b738-1f99-4da9-ab73-c35ae044a3d5"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Forward"",
                    ""id"": ""9f0f9c29-8ea0-4738-91a8-679f27c30afa"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Backward"",
                    ""id"": ""8141f066-5327-49fa-be0c-3e3c516c22b1"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Controller"",
                    ""id"": ""0e037bbe-9c31-45bd-b857-91922da886ef"",
                    ""path"": ""3DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""50f1455e-2107-4ded-b614-9f533e8cf5dd"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""ec39122c-b61d-47c4-8e83-a1d379142308"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""fa9796c1-5edf-4937-b805-db480a1a60b0"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""66e56ecb-169e-4789-a775-28007c0521c5"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Forward"",
                    ""id"": ""9fbd2864-70bd-4ecb-b7b2-4df5401e6c12"",
                    ""path"": ""<NimbusGamepadHid>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Backward"",
                    ""id"": ""05260549-60e0-4272-a2f9-17d95153b36e"",
                    ""path"": ""<NimbusGamepadHid>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6e2446a1-d76a-4fe8-8184-94d55137b3f6"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SprintCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0104854-f14c-481d-a299-ccc476b80d3b"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SprintCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bdcd68a3-8f25-432d-a66d-2ac1a0aee604"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SprintCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""658ec549-c4f5-43cd-b078-c6b330fee395"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""1d7eb77e-e885-4113-92e1-c3b07a7df162"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""e7bce829-34ad-4dcd-8790-c2acfbf7fbe3"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""696a52a4-e660-4f78-81bd-744e5100f9e7"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""664b7a31-d57a-4890-b406-708dc28b2fe5"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""f6c31149-08c9-4577-86e9-38e6c747eecf"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""121d6146-7219-4b14-8bfe-d198f934ee7b"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Scroll_In_Out"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""56871a6d-3a45-4939-a7a2-6a1c4b8b8af9"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42034944-79f1-47b5-be03-95e3e695b0f0"",
                    ""path"": ""<NimbusGamepadHid>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d88fb25-ec8d-4656-a023-5b9ccfbcc55e"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Deselect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d3bb36a-fcc9-4859-9892-16266154c0bb"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Deselect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""847c3ec7-b93e-4df3-b978-c650ae3bd12c"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FollowSpecificObject"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c893146-fdba-4c11-b438-4cceee25da97"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a35d8367-4dd7-4e9c-ab96-e3cdc0639e6a"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""test"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""afb82152-62de-419d-8673-1c6c31dd62ea"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""test"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""ca3247cd-143e-4061-9a7d-c33df2d199e9"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""test"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""69d9335e-4edf-4fae-98e5-5c295e81ed75"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""test"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""c2326c71-ddb8-40f4-b757-fef68f7b9ad4"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateAroundPivot"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""b0b1d2dc-b11f-4d0e-90b5-1c18f20936ad"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateAroundPivot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Binding"",
                    ""id"": ""09a5a0c2-7edd-4726-8f83-31c476574a34"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateAroundPivot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9d6c0fe1-52d8-4b36-96a0-0732ddb241e3"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetPivotPoint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Controller"",
            ""bindingGroup"": ""Controller"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // CameraControll
        m_CameraControll = asset.FindActionMap("CameraControll", throwIfNotFound: true);
        m_CameraControll_Movement = m_CameraControll.FindAction("Movement", throwIfNotFound: true);
        m_CameraControll_SprintCamera = m_CameraControll.FindAction("SprintCamera", throwIfNotFound: true);
        m_CameraControll_RotateCamera = m_CameraControll.FindAction("RotateCamera", throwIfNotFound: true);
        m_CameraControll_Scroll_In_Out = m_CameraControll.FindAction("Scroll_In_Out", throwIfNotFound: true);
        m_CameraControll_Select = m_CameraControll.FindAction("Select", throwIfNotFound: true);
        m_CameraControll_Deselect = m_CameraControll.FindAction("Deselect", throwIfNotFound: true);
        m_CameraControll_FollowSpecificObject = m_CameraControll.FindAction("FollowSpecificObject", throwIfNotFound: true);
        m_CameraControll_RotateAroundPivot = m_CameraControll.FindAction("RotateAroundPivot", throwIfNotFound: true);
        m_CameraControll_OpenMenu = m_CameraControll.FindAction("OpenMenu", throwIfNotFound: true);
        m_CameraControll_test = m_CameraControll.FindAction("test", throwIfNotFound: true);
        m_CameraControll_SetPivotPoint = m_CameraControll.FindAction("SetPivotPoint", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CameraControll
    private readonly InputActionMap m_CameraControll;
    private List<ICameraControllActions> m_CameraControllActionsCallbackInterfaces = new List<ICameraControllActions>();
    private readonly InputAction m_CameraControll_Movement;
    private readonly InputAction m_CameraControll_SprintCamera;
    private readonly InputAction m_CameraControll_RotateCamera;
    private readonly InputAction m_CameraControll_Scroll_In_Out;
    private readonly InputAction m_CameraControll_Select;
    private readonly InputAction m_CameraControll_Deselect;
    private readonly InputAction m_CameraControll_FollowSpecificObject;
    private readonly InputAction m_CameraControll_RotateAroundPivot;
    private readonly InputAction m_CameraControll_OpenMenu;
    private readonly InputAction m_CameraControll_test;
    private readonly InputAction m_CameraControll_SetPivotPoint;
    public struct CameraControllActions
    {
        private @CameraActionMap m_Wrapper;
        public CameraControllActions(@CameraActionMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_CameraControll_Movement;
        public InputAction @SprintCamera => m_Wrapper.m_CameraControll_SprintCamera;
        public InputAction @RotateCamera => m_Wrapper.m_CameraControll_RotateCamera;
        public InputAction @Scroll_In_Out => m_Wrapper.m_CameraControll_Scroll_In_Out;
        public InputAction @Select => m_Wrapper.m_CameraControll_Select;
        public InputAction @Deselect => m_Wrapper.m_CameraControll_Deselect;
        public InputAction @FollowSpecificObject => m_Wrapper.m_CameraControll_FollowSpecificObject;
        public InputAction @RotateAroundPivot => m_Wrapper.m_CameraControll_RotateAroundPivot;
        public InputAction @OpenMenu => m_Wrapper.m_CameraControll_OpenMenu;
        public InputAction @test => m_Wrapper.m_CameraControll_test;
        public InputAction @SetPivotPoint => m_Wrapper.m_CameraControll_SetPivotPoint;
        public InputActionMap Get() { return m_Wrapper.m_CameraControll; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CameraControllActions set) { return set.Get(); }
        public void AddCallbacks(ICameraControllActions instance)
        {
            if (instance == null || m_Wrapper.m_CameraControllActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CameraControllActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @SprintCamera.started += instance.OnSprintCamera;
            @SprintCamera.performed += instance.OnSprintCamera;
            @SprintCamera.canceled += instance.OnSprintCamera;
            @RotateCamera.started += instance.OnRotateCamera;
            @RotateCamera.performed += instance.OnRotateCamera;
            @RotateCamera.canceled += instance.OnRotateCamera;
            @Scroll_In_Out.started += instance.OnScroll_In_Out;
            @Scroll_In_Out.performed += instance.OnScroll_In_Out;
            @Scroll_In_Out.canceled += instance.OnScroll_In_Out;
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
            @Deselect.started += instance.OnDeselect;
            @Deselect.performed += instance.OnDeselect;
            @Deselect.canceled += instance.OnDeselect;
            @FollowSpecificObject.started += instance.OnFollowSpecificObject;
            @FollowSpecificObject.performed += instance.OnFollowSpecificObject;
            @FollowSpecificObject.canceled += instance.OnFollowSpecificObject;
            @RotateAroundPivot.started += instance.OnRotateAroundPivot;
            @RotateAroundPivot.performed += instance.OnRotateAroundPivot;
            @RotateAroundPivot.canceled += instance.OnRotateAroundPivot;
            @OpenMenu.started += instance.OnOpenMenu;
            @OpenMenu.performed += instance.OnOpenMenu;
            @OpenMenu.canceled += instance.OnOpenMenu;
            @test.started += instance.OnTest;
            @test.performed += instance.OnTest;
            @test.canceled += instance.OnTest;
            @SetPivotPoint.started += instance.OnSetPivotPoint;
            @SetPivotPoint.performed += instance.OnSetPivotPoint;
            @SetPivotPoint.canceled += instance.OnSetPivotPoint;
        }

        private void UnregisterCallbacks(ICameraControllActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @SprintCamera.started -= instance.OnSprintCamera;
            @SprintCamera.performed -= instance.OnSprintCamera;
            @SprintCamera.canceled -= instance.OnSprintCamera;
            @RotateCamera.started -= instance.OnRotateCamera;
            @RotateCamera.performed -= instance.OnRotateCamera;
            @RotateCamera.canceled -= instance.OnRotateCamera;
            @Scroll_In_Out.started -= instance.OnScroll_In_Out;
            @Scroll_In_Out.performed -= instance.OnScroll_In_Out;
            @Scroll_In_Out.canceled -= instance.OnScroll_In_Out;
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
            @Deselect.started -= instance.OnDeselect;
            @Deselect.performed -= instance.OnDeselect;
            @Deselect.canceled -= instance.OnDeselect;
            @FollowSpecificObject.started -= instance.OnFollowSpecificObject;
            @FollowSpecificObject.performed -= instance.OnFollowSpecificObject;
            @FollowSpecificObject.canceled -= instance.OnFollowSpecificObject;
            @RotateAroundPivot.started -= instance.OnRotateAroundPivot;
            @RotateAroundPivot.performed -= instance.OnRotateAroundPivot;
            @RotateAroundPivot.canceled -= instance.OnRotateAroundPivot;
            @OpenMenu.started -= instance.OnOpenMenu;
            @OpenMenu.performed -= instance.OnOpenMenu;
            @OpenMenu.canceled -= instance.OnOpenMenu;
            @test.started -= instance.OnTest;
            @test.performed -= instance.OnTest;
            @test.canceled -= instance.OnTest;
            @SetPivotPoint.started -= instance.OnSetPivotPoint;
            @SetPivotPoint.performed -= instance.OnSetPivotPoint;
            @SetPivotPoint.canceled -= instance.OnSetPivotPoint;
        }

        public void RemoveCallbacks(ICameraControllActions instance)
        {
            if (m_Wrapper.m_CameraControllActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICameraControllActions instance)
        {
            foreach (var item in m_Wrapper.m_CameraControllActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CameraControllActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CameraControllActions @CameraControll => new CameraControllActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_ControllerSchemeIndex = -1;
    public InputControlScheme ControllerScheme
    {
        get
        {
            if (m_ControllerSchemeIndex == -1) m_ControllerSchemeIndex = asset.FindControlSchemeIndex("Controller");
            return asset.controlSchemes[m_ControllerSchemeIndex];
        }
    }
    public interface ICameraControllActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnSprintCamera(InputAction.CallbackContext context);
        void OnRotateCamera(InputAction.CallbackContext context);
        void OnScroll_In_Out(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnDeselect(InputAction.CallbackContext context);
        void OnFollowSpecificObject(InputAction.CallbackContext context);
        void OnRotateAroundPivot(InputAction.CallbackContext context);
        void OnOpenMenu(InputAction.CallbackContext context);
        void OnTest(InputAction.CallbackContext context);
        void OnSetPivotPoint(InputAction.CallbackContext context);
    }
}
